### ISSUE TITLE
Samsung Chromebook Plus: The DDK is not compatible

### ISSUE THREAD

**Issue by TheCycoONE** [rockchip-linux/libmali#20] opened 2018-01-08 02:10 UTC
I have a Samsung Chromebook Plus that I loaded ArchLinux ARM on. It is running the linux-gru kernel (https://archlinuxarm.org/packages/aarch64/linux-gru)

I downloaded the libmali-t86x-r14p0-* drivers from this repo and followed the links instructions in the debian folder.

When I try to run weston I get a message:
```
ERROR: The DDK is not compatible with any of the Mali GPUs on the system.
The DDK was built for 0x860 r2p0 status range [0..15], but none of the GPUs matched:
[20:56:15.Jan 07 20:05:37 alarm kernel: mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
Jan 07 20:05:37 alarm kernel: mali ff9a0000.gpu: Probed as mali0
390] failed to initialize display
[20:56:15.390] EGL error state: EGL_NOT_INITIALIZED (0x3001)
```

I checked journalctl I see:

```
Jan 07 20:05:37 alarm kernel: mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
Jan 07 20:05:37 alarm kernel: mali ff9a0000.gpu: Probed as mali0
```

Should these drivers be working with this system and this kernel?

**Comment by Apokalypzx** [comment] 2018-02-21 09:02
I just got the same Chromebook and am looking to setup the Mali drivers, so the outcome of this is important to me as well. 

Looking through your message, the DDK says it's built for "0x860" while your (and my) kernel messages state it is "0x0860". As HEX, these 2 numbers are exactly the same, but if the DDK is parsing it as a string, perhaps there's a mismatch because of the extra "0"?

Just a thought. 

PS, Exactly what steps did you take to "install" the driver? Perhaps, if it ever works, we can get a PKGBUILD pushed to alarm.

**Comment by TheCycoONE** [comment] 2018-02-21 20:42
What I did to install:
Backup first, we will be clobbering some package files
clone this libmali repo
copy the contents of `include` to `/usr/include`
copy `lib/aarch-linux-gnu/libmali-midgard-t86x-r14p0-wayland.so` as  `/usr/lib/libMali.so`
create symlinks as described in https://github.com/rockchip-linux/libmali/blob/rockchip/debian/libmali-rk-midgard-t76x-r14p0-r0p0-wayland.links all inside the `/usr/lib` directory.

I don't recall if I needed more symlinks. I can't have it installed and have a functioning graphical environment so I have since removed it; though I believe it should be possible to run it from /usr/local/ instead.

**Comment by wzyy2** [comment] 2018-02-22 08:49
The mali driver in ChromeOS kernel is not the `r14p0`, you should replace it to use libmali-t86x-r14p0-*.

**Comment by Apokalypzx** [comment] 2018-02-22 09:48
Crap. You're correct. The version compiled in the ChromeOS kernel is r12p0.

And there's no pulling the binary from ChromeOS because that's got a 32bit userland...

Why is it never easy?

**Comment by Apokalypzx** [comment] 2018-02-23 02:17
For those interested, I made a quick PKGBUILD for installing these libs (without headers). I haven't tested to see if it works yet because I still need to build a kernel with the matching mali version. OpenCL complains that there's a version missmatch, so it was able to find the kernel driver and thus *should* work if you have the right version of the kernel driver loaded.
Also, the installation uses /etc/ld.conf.d, so you can install it without bashing mesa in the face.
The repo: https://github.com/Apokalypzx/gru-libgl

**Comment by Apokalypzx** [comment] 2018-03-01 11:03
Confirmed working. These are functional on GRU with the r14 kernel drivers. (Updating the kernel driver is amazingly easy. Just copy the arm driver over the kernel source tree so the directories match. Recompile, fix any errors that pop up, and flash)
I got OpenCL and Wayland to work. I haven't been able to get X11 to work because I haven't been able to get the DDX driver working.

**Comment by TheCycoONE** [comment] 2018-03-01 15:17
Thanks @Apokalypzx 

I guess we can close this?

**Comment by Apokalypzx** [comment] 2018-03-01 15:18
I say yes

**Comment by tuxether** [comment] 2018-04-03 06:08
Should this not be merged upstream? Or at least have instructions on https://archlinuxarm.org/platforms/armv8/rockchip/samsung-chromebook-plus ?

**Comment by Apokalypzx** [comment] 2018-04-03 06:20
@tuxeather You mean the pkgbuild for these binary Mali drivers? I think so, but in the past, when I tried to submit a pkgbuild pull request to archlinuxarm's github, they would deny it and said they don't have time to explain why they denied it. So I gave up.

**Comment by TheCycoONE** [comment] 2018-04-03 10:21
They have accepted wiki updates from me before. That would probably be a good first step. I'm not confident on the kernel side - @Apokalypzx want to try that?

**Comment by epsilontheta** [comment] 2018-04-24 14:11
Unfortunately it does not work for me.

Steps to reproduce:
* install https://github.com/Apokalypzx/gru-libgl on Arch Linux ARM using the ChromeOS kernel 4.4.128  (linux-gru pkg) on the Samsung Chromebook Plus (RK3399)
* execute clinfo, weston-launch or glmark2-drm to get the error
```
ERROR: The DDK is not compatible with any of the Mali GPUs on the system.
The DDK was built for 0x860 r2p0 status range [0..15], but none of the GPUs matched:
Number of platforms                               0
```

Additional infos:
```
dmesg|grep mali
[    0.125005] schedtune: init normalization constants...
[    0.125060] schedtune: using normalization constants mul: 3065780003 sh1: 1 sh2: 12
[    0.125064] schedtune: verify normalization constants...
[    0.626922] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[    0.627405] mali ff9a0000.gpu: Protected mode not available
[    0.627850] mali ff9a0000.gpu: Error -22, no DT entry: mali-simple-power-model.static-coefficient = 1*[0]
[    0.627871] mali ff9a0000.gpu: Error -22, no DT entry: mali-simple-power-model.dynamic-coefficient = 1*[0]
[    0.627923] mali ff9a0000.gpu: Using configured power model mali-simple-power-model, and fallback mali-simple-power-model
[    0.628625] mali ff9a0000.gpu: Probed as mali0
```
```
cat /sys/module/mali_kbase/version
r22p0-01rel0 (UK version 11.4)
```
```
cat /sys/class/misc/mali0/device/gpuinfo
Mali-T86x 4 cores r2p0 0x0860
```

`strace clinfo`: [2Jm4ykvF.txt](https://github.com/rockchip-linux/libmali/files/1942997/2Jm4ykvF.txt)

The failing syscall seems to be
```
ioctl(4, _IOC(_IOC_READ|_IOC_WRITE, 0x80, 0, 0x10), 0x7ff3d0b830) = -1 EINVAL (Invalid argument)
```

Is r22p0 kernel space not compatible with r14p0 user space?
Any ideas?

**Comment by Apokalypzx** [comment] 2018-04-24 17:54
For a brief period, the ChromiumOS kernel devs added a hack to allow a lower version userspace with the r22 kernel driver that they upgraded to. This was because they were still using the r12 userspace when they updated the kernel driver to r22. When they got a working version of the userspace r22, they no longer needed the hack, so they removed it...which sucks for us.

The hack that removed support for lower versions of userspace is at this commit in their kernel tree:
https://chromium.googlesource.com/chromiumos/third_party/kernel/+/e2cbf07110aa764869e9e2b4ae5bfcdc862933c5

If you want, you can probably make a reversion patch out of it and apply it to the head of the branch to get support back. The only other way would be to get the r14 kernel drivers straight from ARMs website, drop them into the kernel tree, build it and pray. This is what I did before the ChromiumOS kernel devs upped the kernel driver to r22, but it is considered pretty hacky and could introduce bugs.

**Comment by shadeslayer** [comment] 2018-12-12 10:43
I seem to be hitting the same issue with the kernel from Debian mainline. I seem to have everything setup properly, but not quite sure why libmali can't find the device.

```
root@debian:~# cat /sys/module/mali_kbase/version
r14p0-01rel0 (UK version 10.6)
root@debian:~# cat /sys/class/misc/mali0/device/gpuinfo
Mali-T86x MP4 r2p0 0x0860
```

Any pointers would be appreciated.

**Comment by shadeslayer** [comment] 2018-12-12 10:52
Ah, I figured it out.

While my /dev/mali0 device was chmod'd to 0660 with owner/group set to root:video, my user was not in the video group.

**Closed** 2020-08-11 04:38 UTC
